# Generated by Django 4.2.7 on 2023-12-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpaymentmethod',
            name='method',
            field=models.CharField(choices=[('Contra reembolso', 'Contra reembolso'), ('Pago online', 'Pago online')], default='Contra reembolso', max_length=30, verbose_name='Método de pago'),
        ),
    ]
