# Generated by Django 4.2.7 on 2023-12-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Enviado', 'Sent'), ('Entregado', 'Delivered')], default='Enviado', max_length=30),
        ),
    ]
