# Generated by Django 5.0 on 2023-12-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_customerclaims'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerclaims',
            name='status',
            field=models.CharField(choices=[('Abierto', 'Open'), ('Cerrado', 'Closed')], default='Abierto', max_length=30),
        ),
    ]
