# Generated by Django 4.2.5 on 2023-11-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Bicicleta de montaña', 'Mountain Bike'), ('Bicicleta urbana', 'Urban Bike'), ('Bicicleta de carretera', 'Road Bike'), ('Accesorio', 'Accessory')], default='Bicicleta de montaña', max_length=30),
        ),
    ]
